version: '3.1'
services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx_image
    container_name: nginx_container
    ports:
      - 80:80

  echo_app:
    image: weshigbee/nginx-echo
    container_name: echo_container
    ports:
      - 5000:8080
